version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter:latest

    working_directory: ~/project

    steps:
      - checkout

      # Set up deployment key
      - add_ssh_keys:
          fingerprints:
            - "SHA256:HqwunfBQiTISki1780OMKtVp97O0w665FKNWeTD6cl8"

      - restore_cache:
          keys:
            - flutter-packages-{{ checksum "pubspec.yaml" }}

      - run:
          name: Install dependencies
          command: flutter pub get

      - save_cache:
          key: flutter-packages-{{ checksum "pubspec.yaml" }}
          paths:
            - .dart_tool
            - .packages
            - build

      - run:
          name: Run tests
          command: flutter test

workflows:
  version: 2
  build:
    jobs:
      - build
