version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter:latest

    working_directory: ~/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - flutter-packages-{{ checksum "pubspec.yaml" }}

      - run:
          name: Install dependencies
          command: flutter pub get

      - save_cache:
          key: flutter-packages-{{ checksum "pubspec.yaml" }}
          paths:
            - .dart_tool
            - .packages
            - build

      # Run tests
      - run:
          name: Run tests
          command: flutter test

workflows:
  version: 2
  build:
    jobs:
      - build
