version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter:latest

    working_directory: ~/project

    steps:
      - checkout


      - run:
          name: Install Flutter
          command: |
            git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION --depth 1
            export PATH="$PATH:`pwd`/flutter/bin"

      - run:
          name: Install dependencies
          command: flutter pub get

      - run:
          name: Run tests
          command: flutter test

workflows:
  version: 2
  build:
    jobs:
      - build
