platform :ios do
    lane :beta do
      increment_build_number  # Increment the build number
      build_ios_app           # Build the iOS app
      # upload_to_testflight    # Upload to TestFlight
    end
  end