name: Bump Version and Commit

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.4'  # Replace with your desired Flutter version

    - name: Bump Version
      run: |
        flutter pub get
        current_version=$(awk '/^version:/ {print $2}' pubspec.yaml)
        version_segments=($(echo $current_version | tr '.' ' '))
        major=${version_segments[0]}
        minor=${version_segments[1]}
        patch=${version_segments[2]}

        # Determine version increment type from commit messages
        commit_message=$(git log -1 --pretty=%B)
        if echo "$commit_message" | grep -qi "major"; then
          new_version="$((major + 1)).0.0"
        elif echo "$commit_message" | grep -qi "minor"; then
          new_version="$major.$((minor + 1)).0"
        elif echo "$commit_message" | grep -qi "patch"; then
          new_version="$major.$minor.$((patch + 1))"
        else
          # No specific keyword found, default to patch
          new_version="$major.$minor.$((patch + 1))"
        fi

        sed -i'' -e "s/^version: .*/version: $new_version/" pubspec.yaml

      working-directory: ./

    - name: Create Versions Directory and Files
      run: |
        if [ ! -d "versions" ]; then
          mkdir versions
        fi

        touch versions/dev.txt
        touch versions/prod.txt
        touch versions/uat.txt

        current_date=$(date +"%Y-%m-%d")

        echo "Version: $new_version, Date: $current_date" >> versions/dev.txt
        echo "Version: $new_version, Date: $current_date" >> versions/prod.txt
        echo "Version: $new_version, Date: $current_date" >> versions/uat.txt

    - name: Commit Version Bump and File Updates
      run: |
        git checkout main
        git config --local user.email "cvaruncv1998@gmail.com"
        git config --local user.name "cv-arun"
        git add pubspec.yaml versions/
        git commit -m "Bump version to $new_version and update version files"
        git push -u origin main
