name: Bump Version and Commit

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.4'  # Replace with your desired Flutter version

    - name: Bump Version
      run: |
        flutter pub get
        current_version=$(awk '/^version:/ {print $2}' pubspec.yaml)
        new_version=$(echo "$current_version" | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
        sed -i'' -e "s/^version: .*/version: $new_version/" pubspec.yaml
      working-directory: ./

    - name: Commit Version Bump
      run: |
       echo "Updating local pubspec"
        git checkout main
        git branch -a
        git config --local user.email "cvaruncv1998@gmail.com"
        git config --local user.name "cv-arun"
        git add pubspec.yaml
        git commit -m "Bump version to $NEW_VERSION"
        git push -u origin main
