name: Deploy to Play Store

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.4' # Change this to your Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Upload release APK to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Deploy to Play Store
      uses: wzieba/Fastlane-Action@v3
      with:
        lane: deploy # Change this to your Fastlane lane

